In [11]:
import pandas as pd
import numpy as np
# from sklearn.metrics import mean_absolute_percentage_error
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

In [27]:
hub = 'LGA'
dataDir = '/home/mingyi/Dropbox/UrbanTemporalNetworks/processedData/'
file = dataDir + hub + 'VehicleByHour2018fromHub.csv'

externalDataDir = "/home/mingyi/Dropbox/UrbanTemporalNetworks/HongData/"+hub+'2018/'
extFile = externalDataDir+"external.csv"

In [28]:
df = pd.read_csv(file)
df = df.groupby(['Date','Hour']).agg({'vehicle_count':'sum'}).reset_index()
external = pd.read_csv(extFile)
df = df.merge(external,on=['Date','Hour'])
df = df.drop(columns=['Date','Hour'])
df['lag'] = df['vehicle_count'].shift(1)
df = df.dropna()
# # normalization is a must in NN models
scaler = MinMaxScaler(feature_range = (0, 1))

In [29]:
df

,vehicle_count,arrival,PRCP,SNOW,SNWD,TMAX,DOW,Tue,Wed,Thur,Fri,Sat,Sun,lag
1,24.0,0.0,0.0,0.0,0.0,13.0,0,0,0,0,0,0,0,142.0
2,2.0,1.0,0.0,0.0,0.0,13.0,0,0,0,0,0,0,0,24.0
3,1.0,0.0,0.0,0.0,0.0,13.0,0,0,0,0,0,0,0,2.0
4,17.0,0.0,0.0,0.0,0.0,13.0,0,0,0,0,0,0,0,1.0
5,22.0,0.0,0.0,0.0,0.0,13.0,0,0,0,0,0,0,0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,468.0,11.0,0.0,0.0,0.0,38.0,0,0,0,0,0,0,0,846.0
8756,605.0,13.0,0.0,0.0,0.0,38.0,0,0,0,0,0,0,0,468.0
8757,385.0,8.0,0.0,0.0,0.0,38.0,0,0,0,0,0,0,0,605.0
8758,414.0,8.0,0.0,0.0,0.0,38.0,0,0,0,0,0,0,0,385.0
8759,532.0,9.0,0.0,0.0,0.0,38.0,0,0,0,0,0,0,0,414.0

In [30]:
# Still, training dataset will be from Jan 28th to Oct, testing dataset will be Nov and Dec

for col in df.columns:
    df[col] = df[col].astype(int)
features_set = df.drop(columns=['vehicle_count'])[:-31*24]

labels = df[['vehicle_count']][:-31*24]
features_set, labels = np.array(features_set), np.array(labels)
features_set = np.reshape(features_set, (features_set.shape[0], features_set.shape[1], 1))

In [ ]:
model = Sequential()
model.add(LSTM(units=7*24, return_sequences=True, input_shape=(features_set.shape[1], 1)))
model.add(Dropout(0.2))

model.add(LSTM(units=7*24, return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(units=7*24, return_sequences=False))
model.add(Dropout(0.2))

model.add(Dense(units = 1))
model.compile(optimizer = 'adam', loss = 'mean_absolute_error')

model.fit(features_set, labels, epochs = 50, batch_size = 32)

Epoch 1/50
251/251 [==============================] - 7s 29ms/step - loss: 601.6905
Epoch 2/50
251/251 [==============================] - 8s 31ms/step - loss: 580.3464
Epoch 3/50
251/251 [==============================] - 6s 26ms/step - loss: 561.9559
Epoch 4/50
251/251 [==============================] - 7s 26ms/step - loss: 544.5618
Epoch 5/50
251/251 [==============================] - 6s 26ms/step - loss: 528.1949
Epoch 6/50
251/251 [==============================] - 6s 25ms/step - loss: 476.6842
Epoch 7/50
251/251 [==============================] - 6s 26ms/step - loss: 440.3459
Epoch 8/50
251/251 [==============================] - 6s 25ms/step - loss: 412.9031
Epoch 9/50
251/251 [==============================] - 6s 25ms/step - loss: 389.4088
Epoch 10/50
251/251 [==============================] - 7s 27ms/step - loss: 367.2302
Epoch 11/50
251/251 [==============================] - 7s 27ms/step - loss: 353.7710
Epoch 12/50
251/251 [==============================] - 7s 29ms/step - loss: 340.3888
Epoch 13/50
251/251 [==============================] - 7s 29ms/step - loss: 326.0406
Epoch 14/50
251/251 [==============================] - 7s 29ms/step - loss: 314.0071
Epoch 15/50
251/251 [==============================] - 7s 28ms/step - loss: 303.0301
Epoch 16/50
251/251 [==============================] - 7s 27ms/step - loss: 293.6461
Epoch 17/50
251/251 [==============================] - 7s 30ms/step - loss: 284.8006
Epoch 18/50
251/251 [==============================] - 7s 29ms/step - loss: 277.2853
Epoch 19/50
251/251 [==============================] - 8s 32ms/step - loss: 271.1600
Epoch 20/50
251/251 [==============================] - 13s 52ms/step - loss: 265.8763
Epoch 21/50
251/251 [==============================] - 122s 485ms/step - loss: 262.2374
Epoch 22/50
251/251 [==============================] - 11s 42ms/step - loss: 258.6175
Epoch 23/50
251/251 [==============================] - 10s 39ms/step - loss: 255.9215
Epoch 24/50
251/251 [==============================] - 8s 30ms/step - loss: 253.4539
Epoch 25/50
251/251 [==============================] - 7s 30ms/step - loss: 252.1664
Epoch 26/50
251/251 [==============================] - 7s 28ms/step - loss: 251.4835
Epoch 27/50
251/251 [==============================] - 8s 31ms/step - loss: 250.9603
Epoch 28/50
251/251 [==============================] - 8s 30ms/step - loss: 249.9860
Epoch 29/50
251/251 [==============================] - 8s 31ms/step - loss: 251.2487
Epoch 30/50
251/251 [==============================] - 8s 32ms/step - loss: 250.6359
Epoch 31/50
251/251 [==============================] - 9s 37ms/step - loss: 237.3179
Epoch 32/50
251/251 [==============================] - 8s 30ms/step - loss: 188.6541
Epoch 33/50
251/251 [==============================] - 7s 27ms/step - loss: 168.3331
Epoch 34/50
251/251 [==============================] - 9s 37ms/step - loss: 152.7600
Epoch 35/50
251/251 [==============================] - 53s 211ms/step - loss: 144.1340
Epoch 36/50
164/251 [==================>...........] - ETA: 1:26 - loss: 139.8950

In [ ]:
model.summary()

### test

In [25]:

features_set_test = df.drop(columns=['vehicle_count'])[-31*24:]
labels_test = df[['vehicle_count']][-31*24:]

features_set_test, labels_test = np.array(features_set_test), np.array(labels_test)
features_set_test = np.reshape(features_set_test, (features_set_test.shape[0], features_set_test.shape[1], 1))

predictions = model.predict(features_set_test)

print('out of sample r2',r2_score(labels_test,predictions))

out of sample r2 0.8263155597013385

In [26]:
# mape could be probmatic as is may lead to division by 0
# add 1 to both residual and real value to prevent infinite values
insample = model.predict(features_set)

print('insample r2',r2_score(labels,insample))

insample r2 0.7986069377462941