In [1]:
import pandas as pd
from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.multioutput import MultiOutputRegressor
import warnings
warnings.filterwarnings('ignore')

### Helper Functions

In [2]:
def loadData(file):
    data = pd.read_csv(file)
    print('Raw shape: ',data.shape)
    data['Date'] = pd.to_datetime(data.Date)
    print('Days: ',len(set(data.Date)))
    return data

In [3]:
def getTimeSeries(df):
    table = pd.pivot_table(df, values='vehicle_count', index=['Date','Hour'],
                    columns=['DOLocationID'], aggfunc=np.sum, fill_value=0)
    return table

In [4]:
def zscoreNormalizeSpatial(matrix):
    m = matrix.copy()
    for i in range(m.shape[0]):
        m[i, :] = (m[i, :] - m[i, :].mean()) / (m[i, :].std()+1e-10)
        
    return m

In [5]:
def standardize(matrix):
    m = matrix.copy()
    scaler = StandardScaler()
    scaler.fit(m)
    t = scaler.transform(m)
    return scaler, t
def inverse_standardize(matrix, scaler):
    t = matrix.copy()
    return scaler.inverse_transform(t)
def getPCAFeatures(matrix, n=10):
    pca = PCA(n_components=n)
    pca.fit(matrix)
    reducedMatrixPCA = pca.transform(matrix)
    reducedMatrixPCA.shape

    reducedDict = {str(i+1):reducedMatrixPCA[:,i] for i in range(reducedMatrixPCA.shape[1])}
    reducedDf = pd.DataFrame(reducedDict)
    #reducedDf.index = index
    return pca,reducedDf

In [6]:
def inverse_standardize(matrix, scaler):
    t = matrix.copy()
    return scaler.inverse_transform(t)

In [7]:
def getPCAFeatures(matrix, n=10):
    pca = PCA(n_components=n)
    pca.fit(matrix)
    reducedMatrixPCA = pca.transform(matrix)
    reducedMatrixPCA.shape

    reducedDict = {str(i+1):reducedMatrixPCA[:,i] for i in range(reducedMatrixPCA.shape[1])}
    reducedDf = pd.DataFrame(reducedDict)
    #reducedDf.index = index
    return pca,reducedDf

In [8]:
def PCA_test(matrix, pca):

    reducedMatrixPCA = pca.transform(matrix)

    reducedDict = {str(i+1):reducedMatrixPCA[:,i] for i in range(reducedMatrixPCA.shape[1])}
    reducedDf = pd.DataFrame(reducedDict)
    #reducedDf.index = index
    return reducedDf

In [9]:
def inverse_pca(matrix,pca):
    m = matrix.copy()
    return pca.inverse_transform(m)

In [10]:
def addLag(dataset, maxlag, lagColumns):
    dataset_list = [dataset]

    for l in range(1, maxlag+1):
        df = dataset.shift(l)
        df = df[lagColumns]
        df.columns = [c+'_lag_'+str(l) for c in df.columns]
        dataset_list.append(df)

    dataset = pd.concat(dataset_list, axis=1).dropna()
    return dataset

In [11]:
def get_rmse(matrix1, matrix2):
    sumSquareError = np.mean(np.power(matrix1 - matrix2,2))
    rmse = np.power(sumSquareError,0.5)
    return rmse

#### Preparing Data

In [12]:
hub = 'JFK'
tune_hyp_params = False
pca_comps = 6

In [13]:
dataDir = '/home/mingyi/Dropbox/UrbanTemporalNetworks/processedData/'
file = dataDir + hub + 'VehicleByHour.csv'

In [14]:
# file = '/home/urwa/Documents/Projects/NYU Remote/project/data/JfkVehiceByHour.csv'

In [15]:
data = loadData(file)

Raw shape:  (2260080, 4)
Days:  365

In [16]:
data = getTimeSeries(data)

In [17]:
data.shape

(8760, 258)

In [18]:
data

DOLocationID     1    2    3    4    5    6    7    8    9    10   ...  254  \
Date       Hour                                                    ...
2018-01-01 0       1    0    0    1    0    0    5    0    0    7  ...    0
           1       0    0    1    1    0    0    1    0    1    4  ...    0
           2       0    0    0    1    0    0    1    0    0    1  ...    0
           3       0    0    0    0    0    0    0    0    0    0  ...    0
           4       0    0    0    0    0    0    0    0    0    3  ...    0
...              ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2018-12-31 19      1    0    0    4    0    1    6    0    1   11  ...    1
           20      4    0    0    0    1    0   11    0    0   19  ...    0
           21      0    0    0    2    0    0   11    0    0    6  ...    0
           22      0    0    3    5    0    0    2    0    1   12  ...    2
           23      1    0    2    2    0    0    6    0    2   16  ...    0

DOLocationID     255  256  257  258  259  260  261  262  263
Date       Hour
2018-01-01 0       2    4    0    0    2    3    0    5    6
           1       2    2    1    1    0    2    0    0    1
           2       0    1    0    1    0    1    0    2    0
           3       1    0    0    2    0    0    0    0    1
           4       0    1    0    1    0    0    0    0    0
...              ...  ...  ...  ...  ...  ...  ...  ...  ...
2018-12-31 19     10    6    4    1    1    3    4   10   16
           20     14   12    3    1    1    6    3   12   14
           21     12    5    6    4    0    1    4    8   14
           22      7    8    4    2    2    0    3   13    9
           23      8    1    6    3    0    3    1    6    9

[8760 rows x 258 columns]

In [19]:
matrix = data.values.astype(np.float64)

In [20]:
scaler, s_matrix = standardize(matrix)

In [21]:
pca,pcaData = getPCAFeatures(s_matrix,n=pca_comps)

In [22]:
pcaData.index = data.index
pcaData = pcaData.reset_index()

In [23]:
pcaData.to_csv('../../processedData//%spca%s.csv'%(hub.upper(),pca_comps),
               index=False)

In [24]:
externalDataDir = "/home/mingyi/Dropbox/UrbanTemporalNetworks/HongData/"
extFile = externalDataDir + hub.upper() + ".csv"

In [25]:
extDf = pd.read_csv(extFile)
print(extDf.shape)
extDf.head(2)

(8760, 46)

,date,arrival,fhv,yellow,vehicle,ifmon,iftue,ifwed,ifthu,iffri,...,maxtemp,mintemp,avgtemp,departure,hdd,cdd,participation,newsnow,snowdepth,ifSnow
0,18/1/1 0:00,6,263,174,437,1,0,0,0,0,...,18,7,12.5,-21.2,52,0,0.0,0.0,0,0
1,18/1/1 1:00,6,138,133,271,1,0,0,0,0,...,18,7,12.5,-21.2,52,0,0.0,0.0,0,0

In [26]:
extDf['date'] = pd.to_datetime(extDf['date'], yearfirst=True)
extDf.head(2)

,date,arrival,fhv,yellow,vehicle,ifmon,iftue,ifwed,ifthu,iffri,...,maxtemp,mintemp,avgtemp,departure,hdd,cdd,participation,newsnow,snowdepth,ifSnow
0,2018-01-01 00:00:00,6,263,174,437,1,0,0,0,0,...,18,7,12.5,-21.2,52,0,0.0,0.0,0,0
1,2018-01-01 01:00:00,6,138,133,271,1,0,0,0,0,...,18,7,12.5,-21.2,52,0,0.0,0.0,0,0

In [27]:
extDf['Hour'] = extDf['date'].dt.hour
extDf['Dow'] = extDf['date'].dt.dayofweek
extDf['Date'] = extDf['date'].dt.date

In [28]:
extDf.columns

Index(['date', 'arrival', 'fhv', 'yellow', 'vehicle', 'ifmon', 'iftue',
       'ifwed', 'ifthu', 'iffri', 'ifsat', 'ifsun', 'if0', 'if1', 'if2', 'if3',
       'if4', 'if5', 'if6', 'if7', 'if8', 'if9', 'if10', 'if11', 'if12',
       'if13', 'if14', 'if15', 'if16', 'if17', 'if18', 'if19', 'if20', 'if21',
       'if22', 'if23', 'maxtemp', 'mintemp', 'avgtemp', 'departure', 'hdd',
       'cdd', 'participation', 'newsnow', 'snowdepth', 'ifSnow', 'Hour', 'Dow',
       'Date'],
      dtype='object')

In [29]:
selected_columns = ['Date', 'Hour', 'Dow', 'arrival','maxtemp', 'mintemp', 'avgtemp', 'departure', 'hdd',
       'cdd', 'participation', 'newsnow', 'snowdepth', 'ifSnow']

In [30]:
extDf = extDf[selected_columns]

In [31]:
print(pcaData.shape)
print(extDf.shape)

(8760, 8)
(8760, 14)

In [32]:
pcaData['Date'] = pd.to_datetime(pcaData['Date'])
extDf['Date'] = pd.to_datetime(extDf['Date'])

In [33]:
pcaData = pd.merge(pcaData,extDf, on=['Date', 'Hour'], how='inner')
print(pcaData.shape)

(8760, 20)

In [34]:
pcaData.columns

Index(['Date', 'Hour', '1', '2', '3', '4', '5', '6', 'Dow', 'arrival',
       'maxtemp', 'mintemp', 'avgtemp', 'departure', 'hdd', 'cdd',
       'participation', 'newsnow', 'snowdepth', 'ifSnow'],
      dtype='object')

In [35]:
lagColumns = ['1', '2', '3', '4', '5', '6', 'arrival']
# lagColumns = ['1', '2', '3', 'arrival']

DateColumns = ['Date']

targetColumns = ['1', '2', '3', '4', '5', '6']

In [36]:
maxlag = 12

pcaData_lag = addLag(pcaData, maxlag, lagColumns)

pcaData_lag.shape

(8748, 104)

In [37]:
data.columns

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            254, 255, 256, 257, 258, 259, 260, 261, 262, 263],
           dtype='int64', name='DOLocationID', length=258)

In [38]:
pcaData_lag

,Date,Hour,1,2,3,4,5,6,Dow,arrival,...,5_lag_11,6_lag_11,arrival_lag_11,1_lag_12,2_lag_12,3_lag_12,4_lag_12,5_lag_12,6_lag_12,arrival_lag_12
12,2018-01-01,12,-0.392448,-1.105831,3.415481,-0.454025,1.643912,-0.924966,0,10,...,-1.648102,0.232312,6.0,-3.505165,4.193204,1.757605,0.954739,-0.356342,-0.916277,6.0
13,2018-01-01,13,0.954326,-2.004481,1.908803,0.439918,2.183831,-2.325378,0,18,...,-0.540334,0.143899,2.0,-7.880647,3.085524,0.654921,1.298047,-1.648102,0.232312,6.0
14,2018-01-01,14,8.897264,-2.689726,5.589648,-0.269981,2.407486,-1.487106,0,19,...,-0.386718,0.174567,0.0,-12.716046,0.426541,1.781059,-0.142437,-0.540334,0.143899,2.0
15,2018-01-01,15,10.344075,-2.730192,5.742405,0.790737,1.202385,-2.818379,0,28,...,0.467271,-0.149520,2.0,-13.601960,0.219401,1.632326,-0.069943,-0.386718,0.174567,0.0
16,2018-01-01,16,9.224129,-3.271371,6.913640,-1.741148,2.851038,-0.479464,0,15,...,1.476181,-3.815311,16.0,-12.909346,0.416125,1.030675,-0.586371,0.467271,-0.149520,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2018-12-31,19,11.912532,4.379843,2.766797,1.121404,1.001422,-3.075313,0,12,...,2.111267,-0.618857,13.0,1.680591,1.104775,3.337913,0.281985,0.071319,-0.282936,17.0
8756,2018-12-31,20,8.094268,5.246344,3.402166,-0.338528,-2.769558,-2.647207,0,19,...,1.493411,-0.266635,16.0,4.841005,1.985641,2.964533,1.080956,2.111267,-0.618857,13.0
8757,2018-12-31,21,9.086558,7.522895,4.497183,-0.345165,-1.213694,-0.693965,0,20,...,0.919813,1.087922,13.0,-2.580933,2.234684,0.813276,-0.290943,1.493411,-0.266635,16.0
8758,2018-12-31,22,7.555999,8.062629,1.310686,0.877798,0.585205,-0.400679,0,16,...,-0.134968,-0.772972,9.0,-1.534455,1.379307,1.581933,-0.267482,0.919813,1.087922,13.0
8759,2018-12-31,23,5.234221,8.744530,0.832103,2.210587,-1.322872,-2.134198,0,13,...,-0.005785,1.160014,14.0,-4.975953,0.609070,1.543535,0.208540,-0.134968,-0.772972,9.0

In [39]:
CommR2List = []
EdgeR2List = []
residualDf_list = []
rawList = []
networkPrediction = pd.DataFrame()

for m in range(1,13):
    print()

    print("month: ",m)
    month_index  = pd.to_datetime(pcaData_lag.Date).dt.month == m

    dataset_train = pcaData_lag[~month_index]
    dataset_test = pcaData_lag[month_index]
    print("Train Size: ",dataset_train.shape)
    print("Test Size: ",dataset_test.shape)


    X_train = dataset_train.drop(targetColumns+DateColumns , axis = 1)
    X_test = dataset_test.drop(targetColumns+DateColumns , axis = 1)
    y_train = dataset_train[targetColumns]
    y_test = dataset_test[targetColumns]



    rf2 = RandomForestRegressor(random_state = 2019, n_estimators=150, 
                               min_samples_split=3,
                               min_samples_leaf= 2, 
                               max_features= 'sqrt',
                               max_depth= None, 
                               bootstrap= False)

    rf2.fit(X_train,y_train)

    print("Train R2: ",rf2.score(X_train,y_train))
    test_r2 = rf2.score(X_test,y_test)
    print("Test R2: ",test_r2)


    pca_prediction = rf2.predict(X_test)

    residual = y_test - pca_prediction
    residual_df = dataset_test[['Date','Hour']]
    residual_df = pd.concat([residual_df,pd.DataFrame(residual)], axis =1)

    network_prediction = inverse_pca(pca_prediction,pca)

    network_prediction = inverse_standardize(network_prediction, scaler)
    
    # relu to convert all prediction to positive
#     network_prediction = np.log(1+np.e**network_prediction)
    # round up negative values to 0
#     network_prediction = np.where(network_prediction<0,0,network_prediction)
    network_prediction_df = pd.DataFrame(network_prediction)
    network_prediction_df.columns = data.columns
    networkPrediction = pd.concat([networkPrediction,network_prediction_df])
    edgeMonthIndex = [False] * maxlag + list(month_index)
    edge_r2 = r2_score(data[edgeMonthIndex], network_prediction, multioutput='variance_weighted')
    print("Edge R2: ",edge_r2)


    CommR2List.append(test_r2)
    EdgeR2List.append(edge_r2)
    residualDf_list.append(residual_df)
#     rawList.append()

month:  1
Train Size:  (8016, 104)
Test Size:  (732, 104)
Train R2:  0.9862165177409408
Test R2:  0.7458010030302661
Edge R2:  0.5096072145262696

month:  2
Train Size:  (8076, 104)
Test Size:  (672, 104)
Train R2:  0.9860495212795529
Test R2:  0.783822076091352
Edge R2:  0.5558916663305757

month:  3
Train Size:  (8004, 104)
Test Size:  (744, 104)
Train R2:  0.9858880105208144
Test R2:  0.8277264214738647
Edge R2:  0.5823157149483388

month:  4
Train Size:  (8028, 104)
Test Size:  (720, 104)
Train R2:  0.9862280407045626
Test R2:  0.8057760323780785
Edge R2:  0.5903310552610967

month:  5
Train Size:  (8004, 104)
Test Size:  (744, 104)
Train R2:  0.9857973552955319
Test R2:  0.8353586367666949
Edge R2:  0.5970672252929163

month:  6
Train Size:  (8028, 104)
Test Size:  (720, 104)
Train R2:  0.9858515160005308
Test R2:  0.8331980848588663
Edge R2:  0.5714386982849092

month:  7
Train Size:  (8004, 104)
Test Size:  (744, 104)
Train R2:  0.9860306667414523
Test R2:  0.7974388972714123
Edge R2:  0.5289433823659315

month:  8
Train Size:  (8004, 104)
Test Size:  (744, 104)
Train R2:  0.9861347674963483
Test R2:  0.7637783979492389
Edge R2:  0.5182539310338111

month:  9
Train Size:  (8028, 104)
Test Size:  (720, 104)
Train R2:  0.9856838137168038
Test R2:  0.8456866809732198
Edge R2:  0.60476916234526

month:  10
Train Size:  (8004, 104)
Test Size:  (744, 104)
Train R2:  0.9855918645971105
Test R2:  0.8535766710258487
Edge R2:  0.6272202313826662

month:  11
Train Size:  (8028, 104)
Test Size:  (720, 104)
Train R2:  0.9861339838353813
Test R2:  0.7815784388880699
Edge R2:  0.5733148184196639

month:  12
Train Size:  (8004, 104)
Test Size:  (744, 104)
Train R2:  0.9861171672837825
Test R2:  0.8062935588672457
Edge R2:  0.556827341330764

In [61]:
networkPrediction['Date'] = data.reset_index().iloc[12:]['Date'].values
networkPrediction['Hour'] = data.reset_index().iloc[12:]['Hour'].values
networkPrediction.to_csv('/home/mingyi/Dropbox/UrbanTemporalNetworks/prediction/%sPCA%s.csv'%(hub,pca_comps),index=False)

In [55]:
print(np.mean(CommR2List))
print(np.mean(EdgeR2List))

0.8074986975706757
0.5682737428591443

In [58]:
res_df = pd.concat(residualDf_list, axis = 0)
res_df.to_csv('../../Resid/'+hub+'PCARoundup'+str(pca_comps)+'RFCV.csv',index=False)